# Copyright (C) 2013 - 2019 Wind River Systems, Inc.
# File  : master.yaml
# Author: Lei Yang <Lei.Yang@windriver.com>
# Date  : 18.12.2019

apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-1
---
apiVersion: v1
kind: Service
metadata:
  name: buildbot
  labels:
    app: buildbot
spec:
  ports:
    - port: 8010
      nodePort: 30001
      name: buildbot
    - port: 9989
      targetPort: 9989
      name: worker
  selector:
    app: buildbot
  type: NodePort
---
apiVersion: extensions/v1beta1
#apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildbot
  labels:
    app: buildbot
spec:
  selector:
    matchLabels:
      app: buildbot
  template:
    metadata:
      labels:
        app: buildbot
    spec:
      serviceAccount: service-account-1
      nodeSelector:
         pek-lpgtest7403: "True"
      containers:
      - name: buildbot
        image: buildbot/buildbot-master:master
        env:
        - name: BUILDBOT_CONFIG_DIR
          value: config
        - name: BUILDBOT_CONFIG_URL
          #value: 'https://github.com/leiyang/meta-buildbot-configs/archive/master.tar.gz'
          value: 'https://github.com/leiyang/buildbot-2021/archive/master1.tar.gz'
        - name: BUILDBOT_WORKER_PORT
          value: '9989'
        - name: BUILDBOT_WEB_URL
          value: 'http://localhost:8010/'
        - name: BUILDBOT_WEB_PORT
          value: 'tcp:port=8010'
        ports:
        - containerPort: 8010
        - containerPort: 9989
